package audio.instruments;

/**************
** WARNING - this code automatically generated by Syntona.
** The real source is probably a Syntona patch.
** Do NOT edit this file unless you copy it to another directory and change the name.
** Otherwise it is likely to get clobbered the next time you
** export Java source code from Syntona.
**
** Syntona is available from: http://www.softsynth.com/syntona/
*/

import com.jsyn.ports.UnitOutputPort;
import com.jsyn.unitgen.UnitVoice;
import com.jsyn.unitgen.SawtoothOscillatorBL;
import com.jsyn.unitgen.VariableRateMonoReader;
import com.jsyn.ports.UnitInputPort;
import com.softsynth.shared.time.TimeStamp;
import com.jsyn.unitgen.PassThrough;
import com.jsyn.unitgen.FilterLowPass;
import com.jsyn.data.SegmentedEnvelope;
import com.jsyn.unitgen.Circuit;

public class SubSynth extends Circuit implements UnitVoice {
    // Declare units and ports.
    PassThrough mFrequencyPassThrough;
    public UnitInputPort frequency;
    PassThrough mAmplitudePassThrough;
    public UnitInputPort amplitude;
    PassThrough mOutputPassThrough;
    public UnitOutputPort output;
    SawtoothOscillatorBL mSawOscBL;
    VariableRateMonoReader mMonoRdr;
    SegmentedEnvelope mSegEnv;
    FilterLowPass mLowPass;

    // Declare inner classes for any child circuits.

    public SubSynth() {
        // Create unit generators.
        add(mFrequencyPassThrough = new PassThrough());
        addPort(frequency = mFrequencyPassThrough.input, "frequency");
        add(mAmplitudePassThrough = new PassThrough());
        addPort(amplitude = mAmplitudePassThrough.input, "amplitude");
        add(mOutputPassThrough = new PassThrough());
        addPort(output = mOutputPassThrough.output, "output");
        add(mSawOscBL = new SawtoothOscillatorBL());
        add(mMonoRdr = new VariableRateMonoReader());
        double[] mSegEnvData = {
            0.004218362282878412, 0.8589743589743589,
            0.00694789081885856, 0.49145299145299143,
            0.018362282878411913, 0.46153846153846156,
            0.022158808933002481, 0,
        };
        mSegEnv = new SegmentedEnvelope( mSegEnvData );
        mSegEnv.setSustainBegin( 1 );
        mSegEnv.setSustainEnd( 3 );
        add(mLowPass = new FilterLowPass());
        // Connect units and ports.
        mFrequencyPassThrough.output.connect(mSawOscBL.frequency);
        mSawOscBL.output.connect(mLowPass.input);
        mMonoRdr.output.connect(mSawOscBL.amplitude);
        mLowPass.output.connect(mOutputPassThrough.input);
        // Setup
        frequency.setup(40.0, 164.813778456435, 8000.0);
        amplitude.setup(0.0, 0.5, 1.0);
        mMonoRdr.amplitude.set(1.0);
        mMonoRdr.rate.set(1.0);
        mLowPass.frequency.set(707.4850694871927);
        mLowPass.amplitude.set(1.0);
        mLowPass.Q.set(0.98555005);
    }

    public void noteOn(double frequency, double amplitude, TimeStamp timeStamp) {
        this.frequency.set(frequency, timeStamp);
        this.amplitude.set(amplitude, timeStamp);
        mMonoRdr.dataQueue.queueOn( mSegEnv, timeStamp);
    }

    public void noteOff(TimeStamp timeStamp) {
        mMonoRdr.dataQueue.queueOff( mSegEnv, false, timeStamp);
    }
    
    public UnitOutputPort getOutput() {
        return output;
    }
}
